/* Aarav AI HUD — Vercel-ready JS (Web Speech + mic options) */
class AaravAI {
  constructor(){ this.mediaStream=null; this.audioCtx=null; this.analyser=null; this.recognition=null; this.micDevices=[]; this.isListening=false; this.moods=[{name:'calm',emoji:'🙂',hue:190},{name:'happy',emoji:'😄',hue:180},{name:'focus',emoji:'🧐',hue:200},{name:'alert',emoji:'⚡',hue:50},{name:'thinking',emoji:'🤔',hue:220}]; this.sampleResponses=[{trigger:['lights','light'],response:'Lights are now on.'},{trigger:['weather'],response:\"It's sunny.\"}]; }
  async init(){ this.cache(); this.bind(); this.updateTime(); setInterval(()=>this.updateTime(),1000); this.animateParticles(); await this.enumerateAudio(); this.setupRecognition(); this.setMood('calm'); this.showNotification('Aarav AI ready','success',1400); }
  cache(){ this.timeDisplay=document.getElementById('timeDisplay'); this.aiCore=document.getElementById('aiCore'); this.voiceWaveform=document.getElementById('voiceWaveform'); this.moodEmoji=document.getElementById('moodEmoji'); this.chatToggle=document.getElementById('chatToggle'); this.chatClose=document.getElementById('chatClose'); this.chatSend=document.getElementById('chatSend'); this.chatInput=document.getElementById('chatInput'); this.chatMessages=document.getElementById('chatMessages'); this.chatInterface=document.getElementById('chatInterface'); this.micSelect=document.getElementById('micSelect'); this.micTest=document.getElementById('micTest'); this.startRec=document.getElementById('startRec'); this.langSelect=document.getElementById('langSelect'); this.sensitivity=document.getElementById('sensitivity'); this.levelViz=document.getElementById('levelViz'); this.notificationContainer=document.getElementById('notificationContainer'); this.systemInfoToggle=document.getElementById('systemInfoToggle'); this.systemInfoContent=document.getElementById('systemInfoContent'); this.bgCanvas=document.getElementById('bgParticles'); }
  bind(){ this.aiCore.addEventListener('click',()=>this.toggleListening()); this.chatToggle.addEventListener('click',()=>this.toggleChat()); this.chatClose.addEventListener('click',()=>this.toggleChat()); this.chatSend.addEventListener('click',()=>this.sendMessage()); this.chatInput.addEventListener('keypress',e=>{ if(e.key==='Enter') this.sendMessage(); }); this.micTest.addEventListener('click',()=>this.testMic()); this.startRec.addEventListener('click',()=>this.startRecognition()); this.systemInfoToggle.addEventListener('click',()=>this.toggleSystemInfo()); document.querySelectorAll('.action-btn').forEach(btn=>btn.addEventListener('click',e=>{ this.ripple(btn,e); this.handleQuickAction(btn.dataset.action, btn.querySelector('.action-label')?.textContent); })); document.addEventListener('keydown',e=>{ if(e.code==='Space'){ e.preventDefault(); this.toggleListening(); } if((e.ctrlKey||e.metaKey) && e.key.toLowerCase()==='c'){ e.preventDefault(); this.toggleChat(); } }); }
  updateTime(){ const now=new Date(); this.timeDisplay.textContent = `${now.toLocaleTimeString('en-US',{hour12:false})} • ${now.toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'})}`; }
  setMood(n){ const m=this.moods.find(x=>x.name===n)||this.moods[0]; this.moodEmoji.textContent=m.emoji; this.aiCore.style.filter=`hue-rotate(${m.hue}deg)`; }
  ripple(btn,e){ const r=document.createElement('span'); const rect=btn.getBoundingClientRect(); const size=Math.max(rect.width,rect.height); const x=e.clientX-rect.left-size/2; const y=e.clientY-rect.top-size/2; Object.assign(r.style,{position:'absolute',width:`${size}px`,height:`${size}px`,left:`${x}px`,top:`${y}px`,borderRadius:'50%',background:'rgba(0,212,255,.35)',transform:'scale(0)',pointerEvents:'none',animation:'ripple .6s linear'}); btn.appendChild(r); setTimeout(()=>r.remove(),650); }
  async enumerateAudio(){ try{ const devices = await navigator.mediaDevices.enumerateDevices(); this.micDevices = devices.filter(d=>d.kind==='audioinput'); this.micSelect.innerHTML = this.micDevices.map((d,i)=>`<option value="${d.deviceId}">${d.label||'Microphone '+(i+1)}</option>`).join(''); }catch(e){ console.warn('enumerate error',e); this.showNotification('Cannot list microphones','info',2000); } }
  async testMic(){ try{ const id=this.micSelect.value; if(this.mediaStream) this.stopStream(); this.mediaStream = await navigator.mediaDevices.getUserMedia({audio: id?{deviceId:id}:{}}); this.startMeter(); this.showNotification('Mic test — speaking now','success',2000); setTimeout(()=>this.stopStream(),4000); }catch(e){ console.error(e); this.showNotification('Mic access denied','info',2000); } }
  startMeter(){ if(!this.mediaStream) return; this.audioCtx = new (window.AudioContext||window.webkitAudioContext)(); const src=this.audioCtx.createMediaStreamSource(this.mediaStream); this.analyser=this.audioCtx.createAnalyser(); this.analyser.fftSize=256; src.connect(this.analyser); const data=new Uint8Array(this.analyser.frequencyBinCount); const bars=this.levelViz.querySelectorAll('i'); const loop=()=>{ if(!this.analyser) return; this.analyser.getByteFrequencyData(data); let sum=0; for(let v of data) sum+=v; const rms = sum/data.length/255; const active = Math.min(bars.length-1, Math.floor(rms*(bars.length))); bars.forEach((b,i)=>b.style.background = i<=active ? 'rgba(0,212,255,.9)' : 'rgba(0,212,255,.15)'); requestAnimationFrame(loop); }; loop(); }
  stopStream(){ try{ this.mediaStream.getTracks().forEach(t=>t.stop()); }catch(e){} if(this.audioCtx){ this.audioCtx.close(); this.audioCtx=null; this.analyser=null; } }
  setupRecognition(){ const S = window.SpeechRecognition || window.webkitSpeechRecognition || null; if(!S){ this.showNotification('Web Speech not supported in this browser','info',3000); return; } this.recognition = new S(); this.recognition.interimResults = true; this.recognition.onstart = ()=>{ this.showNotification('Recognition started — speak now','success',1200); this.voiceWaveform.classList.remove('hidden'); }; this.recognition.onresult = (ev)=>{ let txt=''; for(const r of ev.results) txt+=r[0].transcript; this.chatInput.value = txt; if(ev.results[0] && ev.results[0].isFinal){ this.addMsg(txt,'user'); setTimeout(()=>this.addMsg(this.generateResponse(txt),'assistant'),500); } }; this.recognition.onerror = (e)=>{ console.error(e); this.showNotification('Recognition error: '+(e.error||e.message),'info',3000); this.voiceWaveform.classList.add('hidden'); }; this.recognition.onend = ()=>{ this.voiceWaveform.classList.add('hidden'); this.showNotification('Recognition ended','info',1200); }; }
  async startRecognition(){ try{ const id=this.micSelect.value; if(this.mediaStream) this.stopStream(); this.mediaStream = await navigator.mediaDevices.getUserMedia({audio: id?{deviceId:id}:{}}); this.startMeter(); if(this.recognition){ this.recognition.lang = this.langSelect.value==='auto'?'en-US':this.langSelect.value; this.recognition.start(); }else{ this.showNotification('Speech recognition not available','info',2500); } }catch(e){ console.error(e); this.showNotification('Cannot access microphone for recognition','info',2500); } }
  toggleListening(){ this.isListening=!this.isListening; this.aiCore.setAttribute('aria-pressed',String(this.isListening)); this.voiceWaveform.classList.toggle('hidden',!this.isListening); if(this.isListening){ this.showNotification('Listening','success',1000); const mood=this.moods[Math.floor(Math.random()*this.moods.length)]; this.setMood(mood.name); setTimeout(()=>{ if(this.isListening){ this.isListening=false; this.voiceWaveform.classList.add('hidden'); this.showNotification('Stopped (simulated)','info',900); } },6000); }else this.showNotification('Stopped','info',900); }
  toggleChat(){ this.chatInterface.classList.toggle('hidden'); this.chatInput.focus(); }
  sendMessage(){ const t=this.chatInput.value.trim(); if(!t) return; this.addMsg(t,'user'); this.chatInput.value=''; setTimeout(()=>this.addMsg(this.generateResponse(t),'assistant'),600); }
  addMsg(txt,who){ const w=document.createElement('div'); w.className=`message ${who}-message`; const av=document.createElement('div'); av.className='message-avatar'; av.textContent = who==='user'?'U':'A'; const body=document.createElement('div'); body.className='message-content'; body.innerHTML = `<p>${this.escape(txt)}</p>`; w.appendChild(av); w.appendChild(body); this.chatMessages.appendChild(w); this.chatMessages.scrollTop = this.chatMessages.scrollHeight; }
  escape(s){ return s.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
  generateResponse(m){ const mm=m.toLowerCase(); for(const r of this.sampleResponses) for(const t of r.trigger) if(mm.includes(t)) return r.response; const defs=['I understand. How can I assist?','Processing...','Try quick actions.']; return defs[Math.floor(Math.random()*defs.length)]; }
  toggleSystemInfo(){ this.systemInfoContent.style.display = this.systemInfoContent.style.display==='none'?'block':'none'; this.systemInfoToggle.textContent = this.systemInfoToggle.textContent==='▾'?'▸':'▾'; }
  showNotification(msg,type='info',dur=3000){ const n=document.createElement('div'); n.className=`notification ${type}`; n.textContent=msg; this.notificationContainer.appendChild(n); setTimeout(()=>{ n.style.transition='transform .25s ease, opacity .25s ease'; n.style.transform='translateY(6px)'; n.style.opacity='0'; setTimeout(()=>n.remove(),280); }, dur); }
  simulateInfo(){ setInterval(()=>{ document.querySelectorAll('.info-fill').forEach((el,i)=>{ const w=parseInt(el.style.width)||30+i*10; const next=Math.max(8,Math.min(96, w+(Math.random()-.5)*12)); el.style.width=`${next}%`; }); document.querySelectorAll('.info-value').forEach((el,i)=>{ const fill=document.querySelectorAll('.info-fill')[i]; if(fill) el.textContent = fill.style.width; }); if(Math.random()>.7) this.showNotification(['System scan completed','Voice patterns updated','Security check passed'][Math.floor(Math.random()*3)],'success',2200); },3200); }
  animateParticles(){ const c=this.bgCanvas; if(!c) return; const ctx=c.getContext('2d'); let w,h,parts; const init=()=>{ w=c.width=window.innerWidth; h=c.height=window.innerHeight; parts=Array.from({length:Math.min(120,Math.floor(w*h/22000))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*0.6,vy:(Math.random()-.5)*0.6,r:Math.random()*1.6+0.4})); }; const step=()=>{ ctx.clearRect(0,0,w,h); ctx.fillStyle='rgba(0,212,255,.6)'; for(const p of parts){ p.x+=p.vx; p.y+=p.vy; if(p.x<0||p.x>w) p.vx*=-1; if(p.y<0||p.y>h) p.vy*=-1; ctx.globalAlpha=0.35; ctx.beginPath(); ctx.arc(p.x,p.y,p.r,0,Math.PI*2); ctx.fill(); } ctx.strokeStyle='rgba(96,165,250,.18)'; for(let i=0;i<parts.length;i++){ for(let j=i+1;j<parts.length;j++){ const a=parts[i], b=parts[j]; const dx=a.x-b.x, dy=a.y-b.y, d=Math.hypot(dx,dy); if(d<110){ ctx.globalAlpha=(1-d/110)*.6; ctx.beginPath(); ctx.moveTo(a.x,a.y); ctx.lineTo(b.x,b.y); ctx.stroke(); } } } requestAnimationFrame(step); }; init(); step(); window.addEventListener('resize',init); }
}

document.addEventListener('DOMContentLoaded', ()=>{ const app=new AaravAI(); app.init(); });
